server:
  port: 8088
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/go_walk?serverTimezone=Asia/Seoul
    username: root
    password: 1234


  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cos.gowalk.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

  spring:
    security:
      oauth2:
        client:
          registration:
            naver:
              client-id: #{naver_client_id}
              client-secret: #{naver_client_secret}
              scope:
                - name
                - email
                - nickname
              client-name: Naver
              authorization-grant-type: authorization_code
              redirect-uri: http://localhost:8088/login/oauth2/code/naver


          provider:
            naver:
              authorization-uri: https://nid.naver.com/oauth2.0/authorize
              token-uri: https://nid.naver.com/oauth2.0/token
              user-info-uri: https://openapi.naver.com/v1/nid/me
              user-name-attribute: response

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG